name: Build Python APK

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12.6
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'  # Use Python 3.12.6

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-venv git zip unzip openjdk-11-jdk
          sudo apt-get install -y libncurses6:i386 libstdc++6:i386 zlib1g:i386

      # Step 4: Ensure distutils is available
      - name: Install distutils
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip setuptools

      # Step 5: Install Cython and Buildozer
      - name: Install Cython and Buildozer
        run: |
          python3 -m pip install cython buildozer

      # Step 6: Download and set up Android SDK Command-Line Tools
      - name: Set up Android SDK
        run: |
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          rm commandlinetools-linux-9477386_latest.zip
          # Remove existing cmdline-tools directory if it exists
          rm -rf cmdline-tools
          mkdir cmdline-tools
          # Move the extracted contents to cmdline-tools/latest
          mv tools cmdline-tools/latest
          export ANDROID_HOME=~/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

      # Step 7: Install Android SDK Build-Tools and platforms
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-30"

      # Step 8: Build the APK
      - name: Build APK
        run: |
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
          buildozer -v android debug

      # Step 9: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk  # Path to the generated APK file
          
