name: Build Python APK

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12.6
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'  # Use Python 3.12.6

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-venv git zip unzip openjdk-11-jdk
          sudo apt-get install -y libncurses6:i386 libstdc++6:i386 zlib1g:i386

      # Step 4: Ensure distutils is available
      - name: Install distutils
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip setuptools

      # Step 5: Install Buildozer
      - name: Install Buildozer
        run: |
          python3 -m pip install buildozer

      # Step 6: Build the APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # Step 7: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk  # Path to the generated APK file
